puppetlabs/puppet_jenkins_shared_libraries

src/com/puppet/jenkinsSharedLibraries/Beaker.groovy, src/com/puppet/jenkinsSharedLibraries/BeakerHostgenerator.groovy, src/com/puppet/jenkinsSharedLibraries/BundleExec.groovy, src/com/puppet/jenkinsSharedLibraries/BundleInstall.groovy, src/com/puppet/jenkinsSharedLibraries/ChangeDirectory.groovy, src/com/puppet/jenkinsSharedLibraries/RvmEnvironment.groovy, vars/run_installer_shim_acceptance.groovy
This commit adds various library functions and helpers to facilitate
acceptance testing for pe-installer-shim. There are probably a number of
improvements that can be made, and there are currently some hacky pieces
of this to work around an interesting lack of auth/persistence that
occurs on some of our Jenkins hosts
=> (PE-26190) Add shared functions for pe-installer-shim

vars/run_installer_shim_acceptance.groovy
This commit updates the installer-shim acceptance testing script to
accept a PE family parameter and generate the most recent rc- build for
that PE family via redis rather than having a hard-coded PE build that
will quickly become obsolete
=> (maint) Stop hardcoding PE version for installer-shim

vars/update_effective_date.groovy
This creates a function that takes an effective date string, a pe-installer-shim branch, and a ticket identifier, and will update the EFFECTIVE_DATE variable in the shim.  It verifies that the date given is in the correct format, clones and checks out the given branch of pe-installer-shim, modifies the EFFECTIVE_DATE variable, and pushes a commit to origin with that change.
Should be merged with https://github.com/puppetlabs/pe-installer-shim/pull/471
=> (PE-27344) Add update_effective_date function for updating EFFECTIVE_DATE in shim

vars/run_installer_shim_acceptance.groovy
This commit updates the pe-installer-shim's acceptance testing script in
this repo to use Artifactory as the default PE build location, as part
of the work for migrating from Saturn to Artifactory
=> (maint) Update installer-shim to use Artifactory

vars/cut_release_branch.groovy
This PR adds a method that requires two things, a passed in version string, and a
environmental variable that is set by the job that triggers this method GITHUB_PROJECT.
The method will then check out that project, figure out what branch we're basing the
release off of and create that branch.
=> (maint) Add a release branch cutting method

vars/cut_release_branch.groovy
The =~ operator hates \d, so just using [0-9] as a one for one replacemnet.
Tested the inital of statement with a syntax checker and it passed.
=> (maint) Fix up a syntax error with groovy and the =~ operator

vars/bash/pe_integration_release_job_creation.sh
This script takes two parameters:
* The three digit PE release number, 2018.1.9
* The SCM Code name, Irving
It will then generate the following jobs:
* Workspace creation
* Smoke Upgrade
* Non-standard agent job
* pe-integration (full nightly jobs)
The script assumes you are running this from the ci-job-configs base directory.
To do with the script, clone CJC, enter the directory, then when the jobs are created
create a PR and push it up.
=> (maint) Add a script that creates pe-integration release jobs

vars/bash/init_release_job_creation.sh, vars/bash/installer_vanagon_release_job_creation.sh, vars/bash/integration_release_job_creation.sh, vars/bash/jar_jar_release_job_creation.sh, vars/bash/modules_vanagon_release_job_creation.sh
This pr updates our cjc job scripts to  push up the branch and open a PR to master, along with some naming convention and workflow changes
=> (PE-28152) add github processes to cjc editing scripts

vars/cut_release_branch.groovy, vars/init_release_job_creation.groovy, vars/installer_vanagon_release_job_creation.groovy, vars/integration_release_job_creation.groovy, vars/jar_jar_release_job_creation.groovy, vars/modules_vanagon_release_job_creation.groovy, vars/tag_for_release.groovy
Our scripts were running on the jenkins master, not the worker agent. This not only does not have the required binaries, like hub, but it is also potentially hazardous. This pr adds the worker label to all activated nodes.
=> (maint) Add worker label to called node blocks

vars/bash/integration_release_job_creation.sh
The non-standard job needs to use the -release job group in order to
get the correct PE build number from redis.
=> (maint) Update the integration non-stanard agent job

vars/bash/cut_release_branch.sh, vars/cut_release_branch.groovy
Instead of using a `branch_from` parameter, this commit updates the
script to instead use a codename. This will hopefully account for the
difference in using versions or codenames as branch names across our
different repos.
The way this will work is that the script will try to check out a branch
by first using the codename, and then will use the version parsing logic
to check out a version branch if the codename checkout fails. This is
not the most elegant solution ever, but should work
=> (maint) Update release branch script to use codename

vars/bash/integration_release_job_creation.sh
The 'kickoff_disabled' property for release branch is inherited from
main settings and if we disable kickoff there for mainline pipeline
release pipeline also won't be kicked off. So explicitly enable kickoff
for release pipeline
=> Enable kickoff for release branch

vars/bash/integration_release_job_creation.sh
Reverts puppetlabs/puppet_jenkins_shared_libraries#60
If we merge https://github.com/puppetlabs/ci-job-configs/pull/6835 IMO this isn't needed.
=> Revert "Enable kickoff for release branch"

vars/bash/tag_enterprise_dist_next_rc.sh, vars/tag_enterprise_dist_next_rc.groovy
This is used when we are setting up release branches to differentiate the streams
nitpicks on making the bash script prettier/better are welcome! 
job: https://cinext-jenkinsmaster-pipeline-prod-1.delivery.puppetlabs.net/job/enterprise-dist_release_branch_creation/
```
+ : === Checking out release branch 9999.9.9-release
+ git checkout 9999.9.9-release
Switched to a new branch '9999.9.9-release'
Branch 9999.9.9-release set up to track remote branch 9999.9.9-release from origin.
+ : === Pushing empty commit to 9999.9.9-release and tagging next rc
+ bundle exec rake new_release:push_empty_commit PE_BRANCH_NAME=9999.9.9-release
Creating and pushing empty commit to 9999.9.9-release
+ bundle exec rake new_release:create_and_push_rc_tag PE_BRANCH_NAME=9999.9.9-release
From …
```
=> (RE-13292) Add script for tagging enterprise-dist rc tags

vars/bash/integration_release_job_creation.sh
This pr uses `sed` to add release jobs at anchor points , instead of simply appending at EOF as previously done. This is to help avoid merge conflicts created when multiple jobs are awaiting pr review
=> (PE-29039) Update ingetration creation to use anchor points

vars/bash/installer_team_release_creation_job.sh, vars/installer_team_release_creation_job.groovy
When creating individual PRs for each of the release job update, PR
testing time increases and also need to keep track of all the PRs for
manual merging. Instead, create a single PR combining all of the changes
with individual commit for each of the file update to reduce clutter and
testing time
=> PE-29036 Create a single PR for creating all of release pipelines

vars/bash/installer_team_release_creation_job.sh
upgrader_smoke_platform_axis_flatten_split will now be defined at the top level of the file, or the supported upgrade defaults level.
=> (maint) Update the install script to remove some gratitious config

vars/bash/tag_for_release.sh
This change prevents the tagging script from adding a new tag if the HEAD of the branch is already tagged.
=> (maint) Don't tag if HEAD is already tagged

vars/bundleExec.groovy, vars/bundleInstall.groovy
Some testing pipelines will only need very basic ruby commands like
`bundle install..` and `bundle exec rake...`. By adding these basic
helpers we can avoid polluting the `vars` directory with every teams
bespoke pipeline calling commands, and we can avoid having to use the
`script` stage task in declaritive pipelines.
If we don't add these helpers then there is no easy way to access the
classes defined in files like `BundleInstall.groovy` from declaritive
pipelines without having to use a `script` step in Jenkinsfiles.
=> Add Ruby Helper Vars

vars/bash/tag_enterprise_dist_next_rc.sh, vars/tag_enterprise_dist_next_rc.groovy
currently the job guesses the tag based on the branch_from branch
but since sometimes we dont immediately cut the LTS from master,
there are times where we want a different tag. or say, if we want
to jump to a 2020 version. also added the populate_pe_repos command
in there too, so needed to add the artifactory creds along with it.
this has been tested with the tagging + branch, the access to artifactory
worked but the population itself failed because the funkiness of package
versions on the 9999.9.x branch
=> (RE-13636) Add ability for user to specify next PE tag

vars/bash/installer_team_release_creation_job.sh, vars/bash/release_job_reverts.sh
This modifies the installer_team_release_creation_job script to work with the recent changes in pe-integration.yaml and pe-modules.yaml, and adds pe-backup-tools and pe_installer. It also changes CODENAME to MAINLINE_BRANCH to add some clarity to what that variable is mostly being used for, changes PE_FAMILY to X_Y for additional clarity, adds some extra comments to the yaml files, sets kickoff times for pipelines and disables mainline CI pipelines (except for main), and all changes are now in a single commit instead of several.
=> (PE-30014) Fix up installer_team_release_creation_job 

vars/bash/installer_team_release_creation_job.sh, vars/bash/move_ci_pipeline_kickoff.sh, vars/move_ci_pipeline_kickoff.groovy
This adds a script that allows you to change CI pipeline kickoff times. It uses hub to open a PR and verify that PR checks complete successfully, before merging the PR automatically.
If the hour given is -1, then it disables the pipeline instead.
Generally, this script won't be used directly, but by a set of jobs that will be triggered by Kerminator with the correct values.
=> (maint) Add script for changing CI kickoff times 

vars/bash/move_ci_pipeline_kickoff.sh
If a previous PR failed to merge automatically, it would leave the temp branch in place on ci-job-configs, and a subsequent run of this script would fail.  This force pushes the temp branch so even if it already exists, it will be modified for the latest run of the script.
=> (maint) Force push temp branch in move_ci_pipeline_kickoff

vars/bash/move_ci_pipeline_kickoff.sh
Because ci-job-configs requires a review on all PRs, when hub tries to hit the merge endpoint, it will think it failed.  However, puppetlabs-jenkins has admin on the repo, and it appears the merge actually does happen. So this allows for the failure exit code, and just double checks that the merge actually happened afterwards.
=> (maint) Fix move_ci_pipline_kickoff merge error

vars/run_installer_shim_acceptance.groovy
Because we now can only access centos6 and ubuntu 16.04 VMs through ABS, we need to move the pe-installer-shim acceptance tests to use ABS rather than VMPooler.
=> (maint) Use ABS for pe-installer-shim acceptance

vars/run_installer_shim_acceptance.groovy
Reverts puppetlabs/puppet_jenkins_shared_libraries#92
More work is needed to get ABS to work with Jenkinsfile-based pipelines.  Since this was only to get 2018.1.x working, and since we confirmed it is going away in 10 days, we'll just leave this using vmpooler for the time being.
=> Revert "(maint) Use ABS for pe-installer-shim acceptance"

vars/bash/installer_team_release_creation_job.sh
Bash needs a truly ridiculous number of escapes in order to get the 'export pe_ver' line right in the pe-backup-tools release branch job creation function. This commit feeds Bash's backslash addiction.
=> (maint) Fix escaping in pe-backup-tools release job creation

vars/bash/installer_team_release_creation_job.sh
Disable dogfooding and z-to-z upgrade job in release branch
=> Disable dogfooding and z-to-z upgrade jobs

vars/bash/installer_team_release_creation_job.sh
The regular pipeline will grab the version from the LATEST file on artifactory, but the release dir doesn't contain this file, so we need to specify pe_ver instead.
=> (maint) Fix pe-backup-tools release pipeline

vars/bash/installer_team_release_creation_job.sh
We should no longer specify the Ruby version to use in the pe_installer-promote pipeline and instead use the default, since 2.5.1 is too old for running specs now.
=> (maint) Remove Ruby version override in pe_installer-promote
